export { default as Login } from './auth/Login'
export { default as ResetPassword } from './auth/ResetPassword'
export { default as ForgotPassword } from './auth/ForgotPassword'
export { default as Home } from './home'
export { default as Landing } from './landing'